### ISSUE TITLE
Multiple cameras

### ISSUE THREAD

**Issue by VE7OES** [QuinnDamerell/OctoPrint-OctoEverywhere#10]
On my Octopi, I have 3 cameras.  Under this app though I am only able to access one of them, the first one that was initially setup.  Is there a way to rectify this?

Hans/VE7OES

**Comment by QuinnDamerell** [comment]
Hey! Sorry for the super delay. What this system does is just gives you access to your full OctoPrint interface anywhere! It also enables apps to access your system remotly. So if you're normal portal or app can use multiple cameras, this system should allow it as well!

If it doesn't work or you have any more questions, let me know and I would be happy to help!
