### ISSUE TITLE
Octoeverywhere crashes octoprint after a few seconds of connecting

### ISSUE THREAD

**Issue by berkeoznalbant** [QuinnDamerell/OctoPrint-OctoEverywhere#13]
As I have said in the title. Octoprint crashes each time I connect it with octoeverywhere. [Here](https://github.com/QuinnDamerell/OctoPrint-OctoEverywhere/files/5793226/octoprint.2.log) is the log. On line 3595 it crashes in the logs.

**Comment by QuinnDamerell** [comment]
Thanks for the report! That's very strange, I don't think the plugin should be able to crash OctoPrint at all. What hardware are you running on?

**Comment by berkeoznalbant** [comment]
I'm running raspberry pi 3B+ with original adapter. After octoprint crashing, I can restart it with SSH connection from laptop.

**Comment by QuinnDamerell** [comment]
Closing this for now due to its age. Try installing the latest version and let me know if you are still having trouble!
