### ISSUE TITLE
Setup not working

### ISSUE THREAD

**Issue by mmaslovpy9i** [QuinnDamerell/OctoPrint-OctoEverywhere#14]
I clicked the "finish setup" button and it brought me to this page:

https://octoeverywhere.com/getstarted?printerid=4TZVDFCTPHW4L8ZNF38LOAIKZW9Z0FOMQQXTS23U

Then I've got "printer id not found" error in the screenshot attached.

![Screen Shot 2021-02-19 at 1 54 54 PM](https://user-images.githubusercontent.com/79338721/108565782-237fe580-72ba-11eb-9056-58ba9b991293.png)

Please help!

**Comment by QuinnDamerell** [comment]
Hey @mmaslovpy9i! Can you follow the steps here https://octoeverywhere.com/gatherlogs and send me an email at support@octoeverywhere.com so we can chat in private? Thanks!

**Comment by QuinnDamerell** [comment]
Hey! Let me know if I can help you out! If not, I will close this for now. :)
