### ISSUE TITLE
Server Part

### ISSUE THREAD

**Issue by spacecabbie** [QuinnDamerell/OctoPrint-OctoEverywhere#18]
Hi is the server/website sourcecode also available ?

**Comment by QuinnDamerell** [comment]
Unforentually right now no. It's on my roadmap, but with the rapid expansion of the project, I have been full-time busy keeping things scaling and expanding. I want to also open source the server-side of things, but at the current moment, it's not nearly clean enough. :)

**Comment by spacecabbie** [comment]
Fair enough.

**Comment by FlorianJa** [comment]
@QuinnDamerell are there any updates on this?
