### ISSUE TITLE
After updating i cant connect to the octopy.

### ISSUE THREAD

**Issue by gorsek1** [QuinnDamerell/OctoPrint-OctoEverywhere#27]
After updating to this version i cant connect to OctoPi... Now i have to reformat and reinstall everithing since its bricked.. 
You should probably wait before updating to this version.

PS: Totally my fault, since I havent checked the release date of this update which was yesterday :D :D :D

**Comment by QuinnDamerell** [comment]
Hey @gorsek1! It's always terrible when OctoPrint gets messed up, and you have to reflash. Regardless if our plugin caused it, if you can share OctoPrint logs with our support team, we would be happy to look and try to help you recover it!

https://octoeverywhere.com/support
