### ISSUE TITLE
I can't get a text

### ISSUE THREAD

**Issue by MarkforU** [QuinnDamerell/OctoPrint-OctoEverywhere#29]
Up to a couple days ago, I was receiving MMS text messages on print status, it stopped working. Today I logged into my account and tried to have it send a text code and got nothing, been trying all day...getting email alerts but texting has stopped. I just subscribed for a year Today also because I've been very happy up till I lost text notifications. Everything was fine, which I included a photo. Now the website shows I still need to add it again, it won't let me...I even get messages that I've had too many codes and wait a hour. Is there a problem? Is there a place to look to for information on not getting the code sent or not receiving text messages and you can't sign back up for them?
This is shot from the last time I received a text. I use TMobile Network 
![Screenshot_20221217-195459_Messages](https://user-images.githubusercontent.com/109319672/208282900-90acd6e7-86f3-4ee4-b247-4dccebe6c5a1.jpg)

**Comment by QuinnDamerell** [comment]
Thanks for sending in this bug! I have been working with my SMS provider to fix this, but it's still not resolved for some users. Can you open a support ticket using the following link so we can chat?

https://octoeverywhere.com/support
