### ISSUE TITLE
Running out of memory during printing with octoeverywhere enabled

### ISSUE THREAD

**Issue by hansvanlin** [QuinnDamerell/OctoPrint-OctoEverywhere#30]
During a print my rpi runs out of memory because  slipstream is cached untill memory is full. The octoprint freezes and serial connection is lost and print stops suddenly.
When plugin is disabled the serial connection is good and the print doesn´t stop.
added a screenshot of the log and memory just before it is full and a movie where the plugin is disabled where memory value is constant.

octoprint 1.8.6
octoeverywhere 1.11.1

![enabled](https://user-images.githubusercontent.com/108009649/213881379-8a0248a9-f965-4880-8139-143fe2c39cdb.png)
![2023-01-21_19-12-octoprintLog](https://user-images.githubusercontent.com/108009649/213881382-5004fd91-59a4-4381-bcbe-5fb0731caffc.png)

https://user-images.githubusercontent.com/108009649/213881386-d64a3df6-125a-48f7-91d4-5cfbd8304b35.mp4

**Comment by QuinnDamerell** [comment]
Hey! Thanks for opening this issue. Can you please submit a support ticket to discuss this more privately? support@octoeverywhere.com

**Comment by hansvanlin** [comment]
Hi Quinn, this week I tested and installed octoeverywhere 2.3.7 and octoprint 1.8.7 and found that this issue is still there.
I started a print and looked via ssh at the memory usage and it increased untill it crashed.
