### ISSUE TITLE
Install script targets wrong moonraker.conf and directory in RatOS.

### ISSUE THREAD

**Issue by miklschmidt** [QuinnDamerell/OctoPrint-OctoEverywhere#40]
Hi! I have several users reporting problems with the octoeverywhere install script modifying the RatOS git repository.
Instead of finding `/home/pi/printer_data/config/moonraker.conf` it finds `/home/pi/printer_data/config/RatOS/moonraker.conf` (which is included by `/home/pi/printer_data/config/moonraker.conf`) modifies that, and dumps its files in `/home/printer_data/config/RatOS/`

Any particular reason it's doing a depth first search here? Or is it looking for specific content in moonraker.conf? What's going on?

**Comment by miklschmidt** [comment]
@QuinnDamerell Awesome! let me know when i can release the horde for a test run! :D

**Comment by miklschmidt** [comment]
Also if there's anything else i can help with, please let me know :)

**Comment by QuinnDamerell** [comment]
@miklschmidt no problem! Can I ask, do you know of anyone who runs multiple instances of moonrakeer and klipper on one RatOS device?

**Comment by miklschmidt** [comment]
@QuinnDamerell None, it's currently not supported :)

**Comment by QuinnDamerell** [comment]
@miklschmidt perfect! Ok, I pushed the new installer to master! I explicitly tested it on RatOS to ensure it discovered things correctly, and it looks good! 

If you find a minute, pull the current repo and run the ./install.sh script again to see if it works for you! If it's currently installed in the wrong location, it should be re-install into the correct place.

**Comment by miklschmidt** [comment]
@QuinnDamerell i ran it on my test machine, and it looks good to me! I've asked the users to give it a go again, i'll let you know if i hear of anymore problems but for now i consider it fixed :)

**Comment by QuinnDamerell** [comment]
Perfect! Thanks for bringing this up and please let me know if you hit any other issues in the future! 

Btw, the installer is safe to run anytime, even for recovery and such. But in this one case, users might have to re-link their printers, because a of files moving around.

**Comment by miklschmidt** [comment]
Excellent, i've issued a PSA on discord letting people know, thanks for the fix!
