### ISSUE TITLE
Can't install OctoEverywhere

### ISSUE THREAD

**Issue by Floris039** [QuinnDamerell/OctoPrint-OctoEverywhere#54]
Running in K1 and K1 Max OS mode
Checking required system packages are installed...
Requirement already satisfied: virtualenv in /usr/lib/python3.8/site-packages (1                 5.1.0)
System package install complete.
Checking Python Virtual Environment For OctoEverywhere...
No virtual environment found, creating one now.
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
/usr/lib/python3.8/site-packages/virtualenv.py:1039: DeprecationWarning: the imp                  module is deprecated in favour of importlib; see the module's documentation for                  alternative uses
  import imp
New python executable in /usr/data/octoeverywhere-env/bin/python3
Also creating executable in /usr/data/octoeverywhere-env/bin/python
Installing setuptools, pip, wheel...done.
Updating PIP if needed... (this can take a few seconds or so)
Requirement already satisfied: pip in /usr/data/octoeverywhere-env/lib/python3.8/site-packages (23.3.2)
Installing or updating required python libs...
ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device

 OctoEverywhere has been installed successfully!

It says that it's installed but it's not working...

**Comment by QuinnDamerell** [comment]
Thanks for making an issue with this! We worked with the community to figure this out and fixed it in our installer script. But you will need to run the following command to fix your local device before running the installer again.

`rm -rf /usr/data/octoeverywhere-env /usr/data/octoeverywhere`

After you run the command, you can just run the install script as normal. Let us know if that helps!
