### ISSUE TITLE
Octoeverywhere.conf resetting on reboot in klipper/fluidd

### ISSUE THREAD

**Issue by frazw** [QuinnDamerell/OctoPrint-OctoEverywhere#55]
Im trying to orient the camera the correct way but the settings file seems to change whatever i alter back to default on reboot. the camera is the right way up in stream until klipper fully boots up.

octoapp seems to work and doesnt change the orientation once it is set which makes me thing it may be a permissions issue?

**Comment by QuinnDamerell** [comment]
OctoEverywhere reads the Moonraker webcam config and tries to match it. So, if you setup your webcam in Mainsail or Fluidd how you want, OctoEverwyhere should do the same! It will update the config file with the setup it finds, unless you disable it by disabling the auto flag. 

It seems that might not be working correctly for you, can you open a support ticket so we can get your logs and help fix it?

https://octoeverywhere.com/support
