### ISSUE TITLE
"code":"key153", "msg": "Unparsed config section [include octoeverywhere-system.cfg] detected

### ISSUE THREAD

**Issue by Sabotin** [QuinnDamerell/OctoPrint-OctoEverywhere#56]
Ever since installing Octoeverywhere, Fluidd started showing this warning. Everything works just fine though, it's just that it really bothers me and I would like to remove it. Any ideas ?

![Octoeverywhere](https://github.com/QuinnDamerell/OctoPrint-OctoEverywhere/assets/157064768/13d6c784-e578-4ecd-8ea5-61625a55428a)

**Comment by QuinnDamerell** [comment]
Sorry for the delay! Can you open a support message with us so we can get your logs and help you out?

https://octoeverywhere.com/support
