### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by RyanEwen** [QuinnDamerell/OctoPrint-OctoEverywhere#59]
Hey guys, 

I would love to see Docker support added :)

In the mean time, I've come up with a hacky workaround myself: https://github.com/RyanEwen/octoeverywhere_bambu_docker

Cheers

**Comment by QuinnDamerell** [comment]
Yes! I'm working on an official docker image, but the community has already made a few (which you found). Feel free to use them until the official image comes out!
