### ISSUE TITLE
Feature request: start/stop webcam via Bambu Connect

### ISSUE THREAD

**Issue by scatterthought** [QuinnDamerell/OctoPrint-OctoEverywhere#67]
With OctoPrint, I was able to set up sudo commands to start the mjpg-streamer service whenever the server connected/disconnected to my printer. This prevented the camera from streaming 24/7, which reduces energy consumption and privacy risk.

I'd like to suggest a similar feature for Bambu Connect. When we enter the URL for the webcam stream, we could also enter the commands for starting/stopping the webcam service. In the OctoEverywhere UI we would need:

- a start/stop button for the webcam
- an option to start when the printer connects to OctoEverywhere, or when a print starts
- an option to stop the printer when the printer disconnects or X minutes after a print ends

Thanks for your great work!

**Comment by QuinnDamerell** [comment]
That's a great idea; I will add it to my TODO list! 

I'm going to close this for now, since I don't know when I will get to it. But feel free to add any more ideas if you have them!
