### ISSUE TITLE
Alternative Cam view not refreshed when replying to "Are You Still There?" message

### ISSUE THREAD

**Issue by edstewbob** [QuinnDamerell/OctoPrint-OctoEverywhere#72]
Using Bambu A1 Mini every 2 minutes on the Quick View screen a message appears that asks "Are You Still There?" requiring a reply to continue viewing. When responding to this message and using the Alternative Cam, the Quick View camera view shows a small question mark in the center of the screen and only shows an image if clicking on Bambu Cam and then back to the Alternative Cam view to see the active print.
<img width="1147" alt="Screenshot 2024-07-01 at 2 34 30 PM" src="https://github.com/QuinnDamerell/OctoPrint-OctoEverywhere/assets/14189782/f72f5ed9-fac0-4800-a80f-c5b620c9f8ed">

**Comment by QuinnDamerell** [comment]
Thanks for reporting that; I haven't seen that before! When the image is broken, if you refresh the page, does the webcam start working again?

**Comment by QuinnDamerell** [comment]
Re-open if this still repos!
