### ISSUE TITLE
Dashboard views partially obscured by progress bar

### ISSUE THREAD

**Issue by RyanEwen** [QuinnDamerell/OctoPrint-OctoEverywhere#75]
Hi there,

Just wanted to report something minor that I would love to see tweaked if possible. On the Dashboard my printers often appear empty, but upon going into Quick View, I can see that they sometimes do have prints on them. This is partially due to the camera angle, but also partially due to the CSS styling of the Dashboard.

Eg:
![image](https://github.com/user-attachments/assets/a3403d3a-a5a3-46e8-9abf-62eee08cec66)
![image](https://github.com/user-attachments/assets/1744019b-248d-4eb3-93cb-2ac053796b1f)

Could you make it so that the progress bar does not cover the feed on the Dashboard?

Sidenote: I find the name Quick View kind of confusing since there's no less quick / larger view. Sometimes I forget this and find myself clicking the thumbnail and other things in hopes of opening the larger view, before finally just clicking Quick View and realizing _that_ is the larger view. 

Cheers

**Comment by QuinnDamerell** [comment]
Hey! Sorry for the delay.

That's a great point. I will try to work on the dashboard UI to fix that. :)
