### ISSUE TITLE
unable to access 'https://github.com/QuinnDamerell/OctoPrint-OctoEverywhere.git/': Could not resolve host: github.com

### ISSUE THREAD

**Issue by jamesonvera** [QuinnDamerell/OctoPrint-OctoEverywhere#78]
fatal: unable to access 'https://github.com/QuinnDamerell/OctoPrint-OctoEverywhere.git/': Could not resolve host: github.com

#=======================================================#
 Cloning OctoEverywhere from
 https://github.com/QuinnDamerell/OctoPrint-OctoEverywhere.git
 failed!

what can i do?

**Comment by QuinnDamerell** [comment]
Hey! This is usually due to a local issue, the error is that the installer script can't do a DNS resolve of github.com. Can you make sure your device is able to access the internet and can access github?

**Comment by jamesonvera** [comment]
I have already verified that the devices can connect directly to the
internet but I cannot make a connection with git
